export const CREATE_POST = "CREATE_POST";
export const AUTHENTICATE = "AUTHENTICATE";
export const LOAD_POSTS = "LOAD_POSTS";
export const USERNAME_CHANGE = "USERNAME_CHANGE";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
